import { LocationsProvider } from "@/app/_context/locations-provider";
import Footer from "./_components/navigation/footer";
import Header from "./_components/navigation/header";
import "@/app/_styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layout">
        <Header />
        <LocationsProvider>
          <div className="layout__outer">
            <div className="layout__inner">{children}</div>
          </div>
        </LocationsProvider>
        <Footer />
      </body>
    </html>
  );
}
