import { LocationsProvider } from "@/_context/locations-provider";
import Footer from "../_components/navigation/footer";
import Header from "../_components/navigation/header";
import "@/styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <LocationsProvider>
          <div className="layout-outer">
            <div className="layout-inner">{children}</div>
          </div>
        </LocationsProvider>
        <Footer />
      </body>
    </html>
  );
}
